### ISSUE TITLE
How to Make use of jpostal in Hosting Environment 

### ISSUE THREAD

**Issue by RajuTalisetty** [openvenues/jpostal#18]
Hi ,

I am using jpostal library as part of java web project(based on the steps mentioned here [jpostal](https://github.com/openvenues/jpostal).) , which is working perfectly in my local Linux server.

Now i want to deploy this application in the hosted server (like amazon/any hosted env),  but before deploy this i need to install all the steps mentioned in the above link, because in my code i have dependency of following line.
AddressParser p = AddressParser.getInstanceDataDir("/some/path");
"./configure --datadir=[]
which is configure path of data directory as part of libpostal installatioin.
I cannot install any packages of libpostal in the hosted envirounment, is there any possibility to bundle all the libpostal dependencies, including data-dir as part of the project.

Thanks,
Raju.

**Comment by thatdatabaseguy** [comment]
Hey @RajuTalisetty, that situation sounds somewhat similar to our Travis CI environment, where we just install everything in the working directory. See the [travls.yml](https://github.com/openvenues/jpostal/blob/master/.travis.yml) for jpostal. There, and in most of the bindings, we don't install libpostal system-wide, we just set ```--prefix``` to a relative path during ```configure``` instead of the default /usr/local, and then make sure the relative dir is on PKG_CONFIG_PATH. Note: Travis runs ```gradle assemble``` automatically so that's not needed in the config. Also, the libsnappy-dev dependency is no longer required in libpostal 1.0, so there should be no runtime dependencies (Autotools and gcc are only required at build-time).

**Comment by RajuTalisetty** [comment]
Thanks @thatdatabaseguy  , I am working on this solution, i will give you an update if i got succeeded.. :)
